import { FileWarning, Info } from 'lucide-react';
import { ScoreGauge } from './ScoreGauge';
import { SeverityChip } from './SeverityChip';
import { FindingCard } from './FindingCard';
import { StageList } from './StageList';

export function ResultsPanel({
  status,
  findings,
  score,
  counts,
  expandedId,
  onToggleFinding,
  stageIndex,
  stages,
  progress,
  language,
}) {
  return (
    <section className="csa-panel">
      {status === 'idle' && (
        <div className="csa-idle">
          <div className="csa-idle-icon">
            <FileWarning size={24} />
          </div>
          <div className="csa-idle-title">Awaiting code input</div>
          <div className="csa-idle-sub">
            Paste a snippet or load a sample, then run an analysis to see findings,
            severity, and remediation guidance appear here.
          </div>
        </div>
      )}

      {status === 'analyzing' && (
        <div className="csa-analyzing">
          <div className="csa-analyzing-meta">
            <span>Scanning code</span>
            <span>{progress}%</span>
          </div>
          <div className="csa-scan-frame">
            <div className="csa-scan-bar" style={{ width: `${progress}%` }} />
          </div>
          <div className="csa-progress-text">{stages[stageIndex]}</div>
          <StageList stages={stages} activeIndex={stageIndex} />
        </div>
      )}

      {status === 'complete' && (
        <div>
          <div className="csa-results-top">
            <ScoreGauge score={score} />
            <div className="csa-summary">
              <div className="csa-summary-title">
                {findings.length === 0
                  ? 'No vulnerability patterns matched this snippet.'
                  : `${findings.length} finding${findings.length === 1 ? '' : 's'} across ${
                      language === 'javascript' ? 'JavaScript' : 'Python'
                    } code`}
              </div>
              <div className="csa-chips">
                {counts.map((count) => (
                  <SeverityChip key={count.severity} severity={count.severity} count={count.count} />
                ))}
              </div>
            </div>
          </div>

          {findings.length > 0 && (
            <div>
              <div className="csa-findings-title">Findings</div>
              <div className="csa-findings-list">
                {findings.map((finding, index) => (
                  <FindingCard
                    key={finding.id}
                    finding={finding}
                    index={index}
                    expanded={expandedId === finding.id}
                    onToggle={() => onToggleFinding(finding.id)}
                  />
                ))}
              </div>
            </div>
          )}
        </div>
      )}

      <div className="csa-footer-note">
        <Info size={12} />
        Findings are generated by a client-side pattern engine and a simulated explanation
        layer for prototype purposes — not a substitute for a full static-analysis tool.
      </div>
    </section>
  );
}
